-- ============================================================
-- MODULE 1C — ÉTAPE 2 : MASKING BASÉ SUR LES TAGS
-- ============================================================
-- Au lieu d'attacher chaque politique colonne par colonne,
-- on attache une politique à un TAG. Toute colonne portant
-- ce tag hérite automatiquement de la politique.
--
-- C'est le passage à l'échelle : 500 tables, 3000 colonnes,
-- une seule commande.
--
-- Pré-requis : 01_masking_policies.sql exécuté
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WORKSHOP_WH;

-- ────────────────────────────────────────────────────────────
-- A. CRÉER LES TAGS DE MASKING (dans VOLTAIRE_GOVERNANCE)
-- ────────────────────────────────────────────────────────────
-- On utilise les tags Snowflake système (SEMANTIC_CATEGORY)
-- ET des tags custom pour les cas non couverts.

CREATE OR REPLACE TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE
  ALLOWED_VALUES 'IDENTIFIANT_DIRECT', 'CONTACT', 'FINANCIER', 'LOCALISATION'
  COMMENT = 'Type de PII — détermine la politique de masking applicable';

CREATE OR REPLACE TAG VOLTAIRE_GOVERNANCE.TAGS.MASKING_NIVEAU
  ALLOWED_VALUES 'STRICT', 'STANDARD', 'LEGER'
  COMMENT = 'Niveau de masking : STRICT=hash/null, STANDARD=partiel, LEGER=troncature';

-- ────────────────────────────────────────────────────────────
-- B. ATTACHER DES POLITIQUES AUX TAGS (tag-based masking)
-- ────────────────────────────────────────────────────────────
-- Une politique par combinaison (tag_value, data_type).
-- Snowflake résout automatiquement la bonne politique pour
-- chaque colonne en fonction de ses tags.

ALTER TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE
  SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_PII_STRING;

-- ────────────────────────────────────────────────────────────
-- C. TAGGER LES COLONNES SENSIBLES (RH — tables principales)
-- ────────────────────────────────────────────────────────────
-- On tague les colonnes. Le masking s'active immédiatement.

ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL MODIFY COLUMN
  NIR SET TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE = 'IDENTIFIANT_DIRECT';

ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL MODIFY COLUMN
  NUMERO_PASSEPORT SET TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE = 'IDENTIFIANT_DIRECT';

ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL MODIFY COLUMN
  PERMIS_CONDUIRE SET TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE = 'IDENTIFIANT_DIRECT';

ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL MODIFY COLUMN
  IBAN SET TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE = 'IDENTIFIANT_DIRECT';

-- ────────────────────────────────────────────────────────────
-- D. TAGGER LES COLONNES CRM
-- ────────────────────────────────────────────────────────────

ALTER TABLE VOLTAIRE_CRM.CLIENTS.ENTREPRISES MODIFY COLUMN
  SIRET SET TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE = 'IDENTIFIANT_DIRECT';

ALTER TABLE VOLTAIRE_CRM.CLIENTS.ENTREPRISES MODIFY COLUMN
  SIREN SET TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE = 'IDENTIFIANT_DIRECT';

ALTER TABLE VOLTAIRE_CRM.CLIENTS.ENTREPRISES MODIFY COLUMN
  NUM_TVA SET TAG VOLTAIRE_GOVERNANCE.TAGS.PII_TYPE = 'IDENTIFIANT_DIRECT';

-- ────────────────────────────────────────────────────────────
-- E. ATTACHER D'AUTRES POLITIQUES DIRECTEMENT (sans tag)
-- ────────────────────────────────────────────────────────────
-- Pour les colonnes avec des types non-STRING, on attache
-- directement la politique (le tag-based masking ne supporte
-- qu'un seul type de retour par tag pour le moment).

ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL MODIFY COLUMN
  DATE_NAISSANCE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_DATE_SENSIBLE;

ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS MODIFY COLUMN
  SALAIRE_BRUT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_SALAIRE;

ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS MODIFY COLUMN
  SALAIRE_NET SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_SALAIRE;

ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS MODIFY COLUMN
  IBAN_VERSEMENT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_IBAN;

ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  EMAIL SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_EMAIL;

ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  TELEPHONE_PORTABLE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_TELEPHONE;

ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  TELEPHONE_FIXE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_TELEPHONE;

ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  DATE_NAISSANCE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_DATE_SENSIBLE;

ALTER TABLE VOLTAIRE_FINANCE.COMPTABILITE.FACTURES MODIFY COLUMN
  MONTANT_HT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_MONTANT;

ALTER TABLE VOLTAIRE_FINANCE.COMPTABILITE.FACTURES MODIFY COLUMN
  MONTANT_TTC SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_MONTANT;

ALTER TABLE VOLTAIRE_FINANCE.COMPTABILITE.FACTURES MODIFY COLUMN
  IBAN_CLIENT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_IBAN;

ALTER TABLE VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS MODIFY COLUMN
  MONTANT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_MONTANT;

ALTER TABLE VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS MODIFY COLUMN
  IBAN_CONTREPARTIE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_IBAN;

-- ────────────────────────────────────────────────────────────
-- F. VÉRIFICATION — QUELLES COLONNES SONT MASQUÉES ?
-- ────────────────────────────────────────────────────────────

SELECT
  POLICY_DB,
  POLICY_NAME,
  REF_DATABASE_NAME AS DB_CIBLE,
  REF_SCHEMA_NAME AS SCHEMA_CIBLE,
  REF_ENTITY_NAME AS TABLE_CIBLE,
  REF_COLUMN_NAME AS COLONNE,
  REF_ARG_COLUMN_NAMES
FROM TABLE(VOLTAIRE_GOVERNANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_DOMAIN => 'ACCOUNT'
))
WHERE POLICY_KIND = 'MASKING_POLICY'
ORDER BY DB_CIBLE, TABLE_CIBLE, COLONNE;

-- ────────────────────────────────────────────────────────────
-- G. VÉRIFICATION — TAGS ET LEURS VALEURS
-- ────────────────────────────────────────────────────────────

SELECT
  TAG_DATABASE,
  TAG_NAME,
  TAG_VALUE,
  OBJECT_DATABASE,
  OBJECT_SCHEMA,
  OBJECT_NAME,
  COLUMN_NAME,
  DOMAIN
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE TAG_NAME = 'PII_TYPE'
  AND DOMAIN = 'COLUMN'
ORDER BY OBJECT_DATABASE, OBJECT_NAME, COLUMN_NAME;
