-- ============================================================
-- MODULE 1C — ÉTAPE 2 : MASKING BASÉ SUR LES TAGS
-- ============================================================
-- Les tags existent DÉJÀ — posés par la classification en 1A :
--   • SENSIBILITE (TRES_SENSIBLE, SENSIBLE, INTERNE)
--   • RGPD (IDENTIFIANT_DIRECT, QUASI_IDENTIFIANT, DONNEE_SENSIBLE)
--   • SEMANTIC_CATEGORY (EMAIL, PHONE_NUMBER, PASSPORT, etc.)
--   • PRIVACY_CATEGORY (IDENTIFIER, QUASI_IDENTIFIER, SENSITIVE)
--
-- On n'a PAS besoin de créer de nouveaux tags ni de tagger
-- manuellement les colonnes. On attache les politiques de
-- masking aux tags existants → passage à l'échelle immédiat.
--
-- Pré-requis : 1A (classification complète) + 1C/01 (politiques)
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WORKSHOP_WH;

-- ────────────────────────────────────────────────────────────
-- A. VÉRIFIER LES TAGS EXISTANTS (posés en Module 1A)
-- ────────────────────────────────────────────────────────────
-- Avant d'attacher quoi que ce soit, on vérifie que les tags
-- sont bien là. Cette requête montre ce que la classification
-- a produit automatiquement.

SELECT
  TAG_NAME,
  TAG_VALUE,
  OBJECT_DATABASE || '.' || OBJECT_SCHEMA || '.' || OBJECT_NAME AS TABLE_CIBLE,
  COLUMN_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE TAG_NAME IN ('SENSIBILITE', 'RGPD')
  AND DOMAIN = 'COLUMN'
ORDER BY TAG_NAME, TAG_VALUE, TABLE_CIBLE, COLUMN_NAME;

-- ────────────────────────────────────────────────────────────
-- B. TAG-BASED MASKING : ATTACHER LES POLITIQUES AUX TAGS
-- ────────────────────────────────────────────────────────────
-- On attache MASK_PII_STRING au tag SENSIBILITE.
-- Toute colonne STRING ayant SENSIBILITE = TRES_SENSIBLE ou
-- SENSIBLE héritera automatiquement du masking.
--
-- C'est LA commande clé : une seule ligne protège des
-- centaines de colonnes.

ALTER TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE
  SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_PII_STRING;

-- ────────────────────────────────────────────────────────────
-- C. POLITIQUES DIRECTES POUR LES TYPES NON-STRING
-- ────────────────────────────────────────────────────────────
-- Le tag-based masking ne supporte qu'un seul type de retour
-- par tag. SENSIBILITE est déjà lié à MASK_PII_STRING (STRING).
-- Pour les colonnes DATE, NUMBER, IBAN, EMAIL, TELEPHONE :
-- on attache directement la politique adaptée.

-- Dates de naissance (DATE)
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL MODIFY COLUMN
  DATE_NAISSANCE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_DATE_SENSIBLE;

ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  DATE_NAISSANCE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_DATE_SENSIBLE;

-- Salaires (NUMBER)
ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS MODIFY COLUMN
  SALAIRE_BRUT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_SALAIRE;

ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS MODIFY COLUMN
  SALAIRE_NET SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_SALAIRE;

-- IBAN (STRING mais politique spécifique — masking partiel, pas hash)
ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS MODIFY COLUMN
  IBAN_VERSEMENT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_IBAN;

ALTER TABLE VOLTAIRE_FINANCE.COMPTABILITE.FACTURES MODIFY COLUMN
  IBAN_CLIENT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_IBAN;

ALTER TABLE VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS MODIFY COLUMN
  IBAN_CONTREPARTIE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_IBAN;

-- Emails (STRING mais politique spécifique — domaine visible)
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  EMAIL SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_EMAIL;

-- Téléphones (STRING mais politique spécifique — 4 derniers chiffres)
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  TELEPHONE_PORTABLE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_TELEPHONE;

ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES MODIFY COLUMN
  TELEPHONE_FIXE SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_TELEPHONE;

-- Montants financiers (NUMBER)
ALTER TABLE VOLTAIRE_FINANCE.COMPTABILITE.FACTURES MODIFY COLUMN
  MONTANT_HT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_MONTANT;

ALTER TABLE VOLTAIRE_FINANCE.COMPTABILITE.FACTURES MODIFY COLUMN
  MONTANT_TTC SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_MONTANT;

ALTER TABLE VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS MODIFY COLUMN
  MONTANT SET MASKING POLICY VOLTAIRE_GOVERNANCE.POLICIES.MASK_MONTANT;

-- ────────────────────────────────────────────────────────────
-- D. VÉRIFICATION — QUELLES COLONNES SONT MASQUÉES ?
-- ────────────────────────────────────────────────────────────

SELECT
  POLICY_NAME,
  REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME AS TABLE_CIBLE,
  REF_COLUMN_NAME AS COLONNE
FROM TABLE(VOLTAIRE_GOVERNANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_RH.EMPLOYES.PERSONNEL', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND = 'MASKING_POLICY'
UNION ALL
SELECT POLICY_NAME,
  REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_RH.PAIE.BULLETINS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND = 'MASKING_POLICY'
UNION ALL
SELECT POLICY_NAME,
  REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_CRM.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_CRM.CONTACTS.PERSONNES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND = 'MASKING_POLICY'
UNION ALL
SELECT POLICY_NAME,
  REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_CRM.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_CRM.CLIENTS.ENTREPRISES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND = 'MASKING_POLICY'
UNION ALL
SELECT POLICY_NAME,
  REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_FINANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.COMPTABILITE.FACTURES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND = 'MASKING_POLICY'
UNION ALL
SELECT POLICY_NAME,
  REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_FINANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND = 'MASKING_POLICY'
ORDER BY 2, 3;
