-- ============================================================
-- MODULE 1B — ÉTAPE 4 : VÉRIFICATION CROSS-RÔLE
-- ============================================================
-- On vérifie que le masking et les projections fonctionnent
-- en basculant entre les rôles.
--
-- NOTE : Les rôles SECURITY_ADMIN, DATA_ANALYST, DATA_ENGINEER
-- sont créés dans le Module 1D. Si 1D n'a pas encore été
-- exécuté, ce script crée des rôles temporaires pour la demo.
--
-- Pré-requis : 01 + 02 + 03 exécutés
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WORKSHOP_WH;

-- ────────────────────────────────────────────────────────────
-- A. CRÉER LES RÔLES SI PAS ENCORE FAIT (Module 1D les affinera)
-- ────────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS SECURITY_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;

GRANT ROLE SECURITY_ADMIN TO ROLE SYSADMIN;
GRANT ROLE DATA_ANALYST TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE SECURITY_ADMIN;
GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE DATA_ENGINEER;

GRANT USAGE ON DATABASE VOLTAIRE_RH TO ROLE SECURITY_ADMIN;
GRANT USAGE ON DATABASE VOLTAIRE_RH TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE VOLTAIRE_RH TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_RH TO ROLE SECURITY_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_RH TO ROLE DATA_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_RH TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_RH TO ROLE SECURITY_ADMIN;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_RH TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_RH TO ROLE DATA_ENGINEER;

GRANT USAGE ON DATABASE VOLTAIRE_CRM TO ROLE SECURITY_ADMIN;
GRANT USAGE ON DATABASE VOLTAIRE_CRM TO ROLE DATA_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_CRM TO ROLE SECURITY_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_CRM TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_CRM TO ROLE SECURITY_ADMIN;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_CRM TO ROLE DATA_ANALYST;

GRANT USAGE ON DATABASE VOLTAIRE_FINANCE TO ROLE DATA_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_FINANCE TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_FINANCE TO ROLE DATA_ANALYST;

GRANT USAGE ON DATABASE VOLTAIRE_DATALAKE TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_DATALAKE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_DATALAKE TO ROLE DATA_ENGINEER;

-- ────────────────────────────────────────────────────────────
-- B. DÉSACTIVER LES RÔLES SECONDAIRES (CRITIQUE)
-- ────────────────────────────────────────────────────────────
-- Par défaut, Snowflake active TOUS les rôles en secondaire.
-- IS_ROLE_IN_SESSION('SECURITY_ADMIN') retourne TRUE même si
-- le rôle actif est DATA_ANALYST, car SECURITY_ADMIN est en
-- secondaire. On doit désactiver ça pour voir le masking.
--
-- En production, c'est le RBAC + network policy qui isole,
-- mais pour la démo c'est un point de vigilance essentiel.

USE SECONDARY ROLES NONE;

-- ────────────────────────────────────────────────────────────
-- C. TEST 1 — VUE SECURITY_ADMIN (accès complet)
-- ────────────────────────────────────────────────────────────

USE ROLE SECURITY_ADMIN;

SELECT EMPLOYE_ID, PRENOM, NOM, NIR, NUMERO_PASSEPORT, DATE_NAISSANCE, IBAN
FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL
LIMIT 5;

-- ────────────────────────────────────────────────────────────
-- D. TEST 2 — VUE DATA_ANALYST (masking partiel)
-- ────────────────────────────────────────────────────────────

USE ROLE DATA_ANALYST;

SELECT EMPLOYE_ID, PRENOM, NOM, PERMIS_CONDUIRE, IBAN, DATE_NAISSANCE
FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL
LIMIT 5;

SELECT CONTACT_ID, PRENOM, NOM, EMAIL, TELEPHONE_PORTABLE, DATE_NAISSANCE
FROM VOLTAIRE_CRM.CONTACTS.PERSONNES
LIMIT 5;

SELECT BULLETIN_ID, EMPLOYE_ID, MOIS, SALAIRE_BRUT, SALAIRE_NET, IBAN_VERSEMENT
FROM VOLTAIRE_RH.PAIE.BULLETINS
LIMIT 5;

-- ────────────────────────────────────────────────────────────
-- E. TEST 3 — VUE DATA_ENGINEER (projection policy test)
-- ────────────────────────────────────────────────────────────

USE ROLE DATA_ENGINEER;

SELECT *
FROM VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS
LIMIT 5;

-- ────────────────────────────────────────────────────────────
-- F. TEST 4 — COMPARAISON CÔTE À CÔTE (retour ACCOUNTADMIN)
-- ────────────────────────────────────────────────────────────

USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES ALL;

SELECT 'ACCOUNTADMIN' AS ROLE_TEST, NIR, NUMERO_PASSEPORT, DATE_NAISSANCE
FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL LIMIT 3;

-- ────────────────────────────────────────────────────────────
-- G. INVENTAIRE COMPLET DES POLITIQUES ACTIVES
-- ────────────────────────────────────────────────────────────

SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME AS TABLE_CIBLE,
  REF_COLUMN_NAME AS COLONNE
FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_RH.EMPLOYES.PERSONNEL', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_RH.PAIE.BULLETINS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_CRM.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_CRM.CONTACTS.PERSONNES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_CRM.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_CRM.CLIENTS.ENTREPRISES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_FINANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.COMPTABILITE.FACTURES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_FINANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(VOLTAIRE_DATALAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
ORDER BY 1, 3, 4;
