-- CERT: D2 Data Protection & Governance (30%) + D3 Auditing (18%) — cross-role verification, policy audit
-- ============================================================
-- MODULE 1C — ÉTAPE 4 : VÉRIFICATION CROSS-RÔLE
-- ============================================================
-- On vérifie que le masking et les projections fonctionnent
-- en basculant entre les rôles créés dans le Module 1B.
--
-- Pré-requis : 1A (classification) + 1B (RBAC) + 1C/01-03
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WORKSHOP_WH;

-- ────────────────────────────────────────────────────────────
-- A. DÉSACTIVER LES RÔLES SECONDAIRES (CRITIQUE)
-- ────────────────────────────────────────────────────────────
-- Par défaut, Snowflake active TOUS les rôles en secondaire.
-- IS_ROLE_IN_SESSION('SECURITY_ADMIN') retourne TRUE même si
-- le rôle actif est DATA_ANALYST, car SECURITY_ADMIN est en
-- secondaire. On doit désactiver ça pour voir le masking.
--
-- En production, c'est le RBAC + network policy qui isole,
-- mais pour la démo c'est un point de vigilance essentiel.

USE SECONDARY ROLES NONE;

-- ────────────────────────────────────────────────────────────
-- B. TEST 1 — VUE SECURITY_ADMIN (accès complet)
-- ────────────────────────────────────────────────────────────

USE ROLE SECURITY_ADMIN;

SELECT EMPLOYE_ID, PRENOM, NOM, NIR, NUMERO_PASSEPORT, DATE_NAISSANCE, IBAN
FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL
LIMIT 5;

-- ────────────────────────────────────────────────────────────
-- C. TEST 2 — VUE DATA_ANALYST : PROJECTION
-- ────────────────────────────────────────────────────────────
-- SELECT * ou SELECT NIR → même résultat : erreur.
-- La projection policy bloque toute projection de la colonne.

USE ROLE DATA_ANALYST;

-- ⚠️  Erreur attendue : Projection policy ... does not allow column NIR to project
SELECT NIR FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL LIMIT 1;

-- ────────────────────────────────────────────────────────────
-- D. INVENTAIRE COMPLET DES POLITIQUES ACTIVES
-- ────────────────────────────────────────────────────────────

USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES ALL;

SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME AS TABLE_CIBLE,
  REF_COLUMN_NAME AS COLONNE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_RH.EMPLOYES.PERSONNEL', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_RH.PAIE.BULLETINS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_CRM.CONTACTS.PERSONNES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_CRM.CLIENTS.ENTREPRISES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.COMPTABILITE.FACTURES', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
UNION ALL
SELECT POLICY_KIND, POLICY_NAME,
  REF_DATABASE_NAME||'.'||REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME,
  REF_COLUMN_NAME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS', REF_ENTITY_DOMAIN => 'TABLE'))
WHERE POLICY_KIND IN ('MASKING_POLICY','PROJECTION_POLICY')
ORDER BY 1, 3, 4;
