-- ============================================================
-- MODULE 1C — ÉTAPE 6 : LE MOMENT DE VÉRITÉ (THE PAYOFF)
-- ============================================================
-- Même requête, 4 rôles différents.
-- Tout ce qu'on a construit (classification + RBAC + masking
-- + projection + RAP) se manifeste en une seule démonstration.
--
-- Pré-requis : Modules 1A + 1B + 1C (01-05) exécutés
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WORKSHOP_WH;
USE SECONDARY ROLES NONE;

-- ────────────────────────────────────────────────────────────
-- A. LA REQUÊTE DE RÉFÉRENCE
-- ────────────────────────────────────────────────────────────
-- On va exécuter cette même requête avec chaque rôle :

-- SELECT EMPLOYE_ID, PRENOM, NOM, DEPARTEMENT, POSTE,
--        PERMIS_CONDUIRE, IBAN, DATE_NAISSANCE
-- FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL
-- LIMIT 10;

-- ────────────────────────────────────────────────────────────
-- B. SECURITY_ADMIN — ACCÈS COMPLET
-- ────────────────────────────────────────────────────────────

USE ROLE SECURITY_ADMIN;

SELECT 'SECURITY_ADMIN' AS ROLE_ACTIF,
  EMPLOYE_ID, PRENOM, NOM, DEPARTEMENT, POSTE,
  PERMIS_CONDUIRE, IBAN, DATE_NAISSANCE
FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL
LIMIT 10;

-- Attendu : toutes les lignes, toutes les colonnes, toutes les valeurs en clair

-- ────────────────────────────────────────────────────────────
-- C. DATA_ANALYST — MASKING + RAP
-- ────────────────────────────────────────────────────────────

USE ROLE DATA_ANALYST;

SELECT 'DATA_ANALYST' AS ROLE_ACTIF,
  EMPLOYE_ID, PRENOM, NOM, DEPARTEMENT, POSTE,
  PERMIS_CONDUIRE, IBAN, DATE_NAISSANCE
FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL
LIMIT 10;

-- Attendu :
--   • LIGNES : seulement Commercial, Marketing, Communication (RAP)
--   • PERMIS_CONDUIRE : hash SHA2 (MASK_PII_STRING via tag SENSIBILITE)
--   • IBAN : FR76****XXXX (masking partiel FR_IBAN via tag)
--   • DATE_NAISSANCE : 1er janvier de l'année (MASK_PII_DATE via tag)

-- ────────────────────────────────────────────────────────────
-- D. DATA_ENGINEER — MASKING + RAP (différents périmètres)
-- ────────────────────────────────────────────────────────────

USE ROLE DATA_ENGINEER;

SELECT 'DATA_ENGINEER' AS ROLE_ACTIF,
  EMPLOYE_ID, PRENOM, NOM, DEPARTEMENT, POSTE,
  PERMIS_CONDUIRE, IBAN, DATE_NAISSANCE
FROM VOLTAIRE_RH.EMPLOYES.PERSONNEL
LIMIT 10;

-- Attendu :
--   • LIGNES : seulement Informatique, R&D, Production (RAP)
--   • PERMIS_CONDUIRE : '***MASQUÉ***' (ni SECURITY_ADMIN ni DATA_ANALYST)
--   • IBAN : '***MASQUÉ***'
--   • DATE_NAISSANCE : NULL

-- ────────────────────────────────────────────────────────────
-- E. CRM — MÊME DÉMONSTRATION AVEC LA TABLE ENTREPRISES
-- ────────────────────────────────────────────────────────────

USE ROLE SECURITY_ADMIN;
SELECT 'SECURITY_ADMIN' AS ROLE_ACTIF,
  COUNT(*) AS NB_ENTREPRISES,
  COUNT(DISTINCT SECTEUR_ACTIVITE) AS NB_SECTEURS
FROM VOLTAIRE_CRM.CLIENTS.ENTREPRISES;

USE ROLE DATA_ANALYST;
SELECT 'DATA_ANALYST' AS ROLE_ACTIF,
  COUNT(*) AS NB_ENTREPRISES,
  COUNT(DISTINCT SECTEUR_ACTIVITE) AS NB_SECTEURS,
  LISTAGG(DISTINCT SECTEUR_ACTIVITE, ', ') AS SECTEURS_VISIBLES
FROM VOLTAIRE_CRM.CLIENTS.ENTREPRISES;

-- ────────────────────────────────────────────────────────────
-- F. SYNTHÈSE — MATRICE DE COUVERTURE
-- ────────────────────────────────────────────────────────────

USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES ALL;

-- Combien de colonnes sont taguées, par tag ?
SELECT TAG_NAME AS TAG,
  COUNT(DISTINCT COLUMN_NAME) AS COLONNES_TAGUEES,
  COUNT(DISTINCT TAG_VALUE) AS VALEURS_DISTINCTES,
  LISTAGG(DISTINCT TAG_VALUE, ', ') WITHIN GROUP (ORDER BY TAG_VALUE) AS VALEURS
FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
  'VOLTAIRE_RH.EMPLOYES.PERSONNEL', 'TABLE'))
WHERE TAG_DATABASE != 'SNOWFLAKE'
GROUP BY TAG_NAME
ORDER BY TAG_NAME;

-- Combien de politiques de chaque type protègent l'ensemble des tables ?
WITH all_refs AS (
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_RH.EMPLOYES.PERSONNEL', REF_ENTITY_DOMAIN => 'TABLE'))
  UNION ALL
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_RH.PAIE.BULLETINS', REF_ENTITY_DOMAIN => 'TABLE'))
  UNION ALL
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_RH.RECRUTEMENT.CANDIDATS', REF_ENTITY_DOMAIN => 'TABLE'))
  UNION ALL
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_CRM.CONTACTS.PERSONNES', REF_ENTITY_DOMAIN => 'TABLE'))
  UNION ALL
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_CRM.CLIENTS.ENTREPRISES', REF_ENTITY_DOMAIN => 'TABLE'))
  UNION ALL
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.COMPTABILITE.FACTURES', REF_ENTITY_DOMAIN => 'TABLE'))
  UNION ALL
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS', REF_ENTITY_DOMAIN => 'TABLE'))
  UNION ALL
  SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS', REF_ENTITY_DOMAIN => 'TABLE'))
)
SELECT POLICY_KIND AS TYPE_POLITIQUE,
  COUNT(DISTINCT POLICY_NAME) AS NB_POLITIQUES,
  COUNT(DISTINCT REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME) AS TABLES_PROTEGEES,
  CASE
    WHEN POLICY_KIND = 'ROW_ACCESS_POLICY' THEN '-'
    ELSE CAST(COUNT(DISTINCT REF_DATABASE_NAME || '.' || REF_ENTITY_NAME || '.' || REF_COLUMN_NAME) AS VARCHAR)
  END AS COLONNES_PROTEGEES
FROM all_refs
GROUP BY POLICY_KIND
ORDER BY POLICY_KIND;
