-- ============================================================
-- MODULE 1B — ÉTAPE 1 : ARCHITECTURE RBAC
-- ============================================================
-- On construit la hiérarchie de rôles proprement :
--   • Rôles d'accès (ce que tu ATTEINS — par database)
--   • Rôles fonctionnels (ce que tu FAIS — par métier)
--   • Hiérarchie avec héritage
--
-- Ces rôles sont utilisés dans le Module 1C (masking, RAP)
-- pour démontrer la protection différenciée par rôle.
--
-- Pré-requis : Module 1A exécuté
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WORKSHOP_WH;

-- ────────────────────────────────────────────────────────────
-- A. RÔLES D'ACCÈS (access roles — ce que tu ATTEINS)
-- ────────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS AR_VOLTAIRE_RH_READ;
CREATE ROLE IF NOT EXISTS AR_VOLTAIRE_RH_WRITE;
CREATE ROLE IF NOT EXISTS AR_VOLTAIRE_CRM_READ;
CREATE ROLE IF NOT EXISTS AR_VOLTAIRE_CRM_WRITE;
CREATE ROLE IF NOT EXISTS AR_VOLTAIRE_FINANCE_READ;
CREATE ROLE IF NOT EXISTS AR_VOLTAIRE_DATALAKE_READ;
CREATE ROLE IF NOT EXISTS AR_VOLTAIRE_DATALAKE_WRITE;

GRANT USAGE ON DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_READ;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_READ;
GRANT SELECT ON ALL VIEWS IN DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_READ;
GRANT USAGE ON ALL FUNCTIONS IN DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_READ;
GRANT USAGE ON ALL PROCEDURES IN DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_READ;

GRANT ROLE AR_VOLTAIRE_RH_READ TO ROLE AR_VOLTAIRE_RH_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL VIEWS IN DATABASE VOLTAIRE_RH TO ROLE AR_VOLTAIRE_RH_WRITE;

GRANT USAGE ON DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_READ;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_READ;
GRANT SELECT ON ALL VIEWS IN DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_READ;
GRANT USAGE ON ALL FUNCTIONS IN DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_READ;
GRANT USAGE ON ALL PROCEDURES IN DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_READ;

GRANT ROLE AR_VOLTAIRE_CRM_READ TO ROLE AR_VOLTAIRE_CRM_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL VIEWS IN DATABASE VOLTAIRE_CRM TO ROLE AR_VOLTAIRE_CRM_WRITE;

GRANT USAGE ON DATABASE VOLTAIRE_FINANCE TO ROLE AR_VOLTAIRE_FINANCE_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_FINANCE TO ROLE AR_VOLTAIRE_FINANCE_READ;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_FINANCE TO ROLE AR_VOLTAIRE_FINANCE_READ;
GRANT SELECT ON ALL VIEWS IN DATABASE VOLTAIRE_FINANCE TO ROLE AR_VOLTAIRE_FINANCE_READ;
GRANT USAGE ON ALL FUNCTIONS IN DATABASE VOLTAIRE_FINANCE TO ROLE AR_VOLTAIRE_FINANCE_READ;
GRANT USAGE ON ALL PROCEDURES IN DATABASE VOLTAIRE_FINANCE TO ROLE AR_VOLTAIRE_FINANCE_READ;

GRANT USAGE ON DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_READ;
GRANT SELECT ON ALL TABLES IN DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_READ;
GRANT SELECT ON ALL VIEWS IN DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_READ;
GRANT USAGE ON ALL FUNCTIONS IN DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_READ;
GRANT USAGE ON ALL PROCEDURES IN DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_READ;

GRANT ROLE AR_VOLTAIRE_DATALAKE_READ TO ROLE AR_VOLTAIRE_DATALAKE_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL VIEWS IN DATABASE VOLTAIRE_DATALAKE TO ROLE AR_VOLTAIRE_DATALAKE_WRITE;

GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE AR_VOLTAIRE_RH_READ;
GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE AR_VOLTAIRE_CRM_READ;
GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE AR_VOLTAIRE_FINANCE_READ;
GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE AR_VOLTAIRE_DATALAKE_READ;

-- ────────────────────────────────────────────────────────────
-- B. RÔLES FONCTIONNELS (functional roles — ce que tu FAIS)
-- ────────────────────────────────────────────────────────────
-- Les rôles fonctionnels héritent des rôles d'accès.

CREATE ROLE IF NOT EXISTS SECURITY_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;

GRANT ROLE AR_VOLTAIRE_RH_READ TO ROLE DATA_ANALYST;
GRANT ROLE AR_VOLTAIRE_CRM_READ TO ROLE DATA_ANALYST;
GRANT ROLE AR_VOLTAIRE_FINANCE_READ TO ROLE DATA_ANALYST;

GRANT ROLE AR_VOLTAIRE_RH_READ TO ROLE DATA_ENGINEER;
GRANT ROLE AR_VOLTAIRE_DATALAKE_WRITE TO ROLE DATA_ENGINEER;

GRANT ROLE AR_VOLTAIRE_RH_WRITE TO ROLE SECURITY_ADMIN;
GRANT ROLE AR_VOLTAIRE_CRM_WRITE TO ROLE SECURITY_ADMIN;
GRANT ROLE AR_VOLTAIRE_FINANCE_READ TO ROLE SECURITY_ADMIN;
GRANT ROLE AR_VOLTAIRE_DATALAKE_WRITE TO ROLE SECURITY_ADMIN;

CREATE ROLE IF NOT EXISTS GLOBAL_VIEWER;
GRANT ROLE AR_VOLTAIRE_RH_READ TO ROLE GLOBAL_VIEWER;
GRANT ROLE AR_VOLTAIRE_CRM_READ TO ROLE GLOBAL_VIEWER;
GRANT ROLE AR_VOLTAIRE_FINANCE_READ TO ROLE GLOBAL_VIEWER;
GRANT ROLE AR_VOLTAIRE_DATALAKE_READ TO ROLE GLOBAL_VIEWER;
GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE GLOBAL_VIEWER;

GRANT ROLE DATA_ANALYST TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE SECURITY_ADMIN TO ROLE SYSADMIN;
GRANT ROLE GLOBAL_VIEWER TO ROLE SYSADMIN;

-- ────────────────────────────────────────────────────────────
-- C. VÉRIFICATION — VISUALISER LA HIÉRARCHIE
-- ────────────────────────────────────────────────────────────

SHOW GRANTS TO ROLE DATA_ANALYST;
SHOW GRANTS TO ROLE DATA_ENGINEER;
SHOW GRANTS TO ROLE SECURITY_ADMIN;
SHOW GRANTS TO ROLE GLOBAL_VIEWER;
