-- ============================================================
-- MODULE 1A — ÉTAPE 3 : CLASSIFICATION MANUELLE
-- ============================================================
-- Première rencontre avec SYSTEM$CLASSIFY : on lance la
-- classification sur une table, on inspecte les résultats,
-- et on découvre les LIMITES de la détection automatique
-- sur des données non-anglophones.
--
-- C'est un moment-clé du workshop : Snowflake détecte bien
-- les patterns universels (email, passeport), mais les formats
-- spécifiquement français (NIR, IBAN FR, +33, noms français)
-- passent souvent à travers les mailles du filet.
--
-- → D'où l'importance des CUSTOM CLASSIFIERS (étape 04).
--
-- Pré-requis : 01 + 02 exécutés (tables chargées)
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WORKSHOP_WH;

-- ════════════════════════════════════════════════════════════
-- PARTIE A : CLASSIFICATION AUTOMATIQUE — PREMIÈRE TENTATIVE
-- ════════════════════════════════════════════════════════════

-- Classifier la table EMPLOYES sans appliquer de tags (mode "dry run").
-- On veut juste voir ce que Snowflake détecte automatiquement.
CALL SYSTEM$CLASSIFY('VOLTAIRE_RH.EMPLOYES.PERSONNEL', null);

-- Le résultat est un objet JSON. Pour le lire facilement :
SELECT
    f.KEY AS NOM_COLONNE,
    f.VALUE:recommendation:semantic_category::STRING AS CATEGORIE_SEMANTIQUE,
    f.VALUE:recommendation:privacy_category::STRING AS CATEGORIE_VIE_PRIVEE,
    f.VALUE:recommendation:confidence::STRING AS CONFIANCE,
    f.VALUE:recommendation:coverage::NUMBER AS COUVERTURE
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) r,
     TABLE(FLATTEN(INPUT => r.$1:classification_result)) f
ORDER BY CATEGORIE_SEMANTIQUE NULLS LAST;

-- ┌─────────────────────────────────────────────────────────┐
-- │  RÉSULTAT ATTENDU : seulement ~3 colonnes détectées !   │
-- │                                                         │
-- │  ✅ EMAIL_PRO         → EMAIL / IDENTIFIER / HIGH       │
-- │  ✅ NUMERO_PASSEPORT  → PASSPORT / IDENTIFIER / HIGH    │
-- │  ✅ PERMIS_CONDUIRE   → DRIVERS_LICENSE / IDENTIFIER    │
-- │                                                         │
-- │  ❌ NOM, PRENOM       → non détectés (noms français)    │
-- │  ❌ TELEPHONE_*       → non détectés (+33 format)       │
-- │  ❌ NIR               → non détecté (sécu française)    │
-- │  ❌ IBAN              → non détecté (FR76...)           │
-- │  ❌ ADRESSE, VILLE    → non détectés                    │
-- │  ❌ DATE_NAISSANCE    → non détecté                     │
-- │                                                         │
-- │  → C'est normal ! SYSTEM$CLASSIFY est optimisé pour     │
-- │    les patterns anglo-saxons. Les données françaises     │
-- │    nécessitent des CUSTOM CLASSIFIERS (étape 04).       │
-- └─────────────────────────────────────────────────────────┘

-- ════════════════════════════════════════════════════════════
-- PARTIE B : APPLIQUER LES TAGS AUTO (sur ce qu'on a trouvé)
-- ════════════════════════════════════════════════════════════

-- Même avec peu de détections, on applique les tags pour voir
-- comment fonctionne le mécanisme auto_tag.
CALL SYSTEM$CLASSIFY('VOLTAIRE_RH.EMPLOYES.PERSONNEL', {'auto_tag': true});

-- Vérifier les tags appliqués (seulement 3 colonnes taggées) :
SELECT
    COLUMN_NAME,
    TAG_NAME,
    TAG_VALUE
FROM TABLE(
    VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
        'VOLTAIRE_RH.EMPLOYES.PERSONNEL', 'TABLE'
    )
)
ORDER BY COLUMN_NAME, TAG_NAME;

-- ════════════════════════════════════════════════════════════
-- PARTIE C : COMPLÉTER MANUELLEMENT — TAGS SYSTÈME
-- ════════════════════════════════════════════════════════════

-- Pour les colonnes que SYSTEM$CLASSIFY a ratées, on peut
-- poser les system tags manuellement. En production, on
-- utilisera des Custom Classifiers (étape 04), mais ici
-- on montre d'abord l'approche manuelle pour comprendre
-- le mécanisme de tagging.

-- Noms & prénoms → NAME / IDENTIFIER
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN NOM SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN NOM SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN PRENOM SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN PRENOM SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';

-- Téléphones → PHONE_NUMBER / IDENTIFIER
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN TELEPHONE_PRO SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'PHONE_NUMBER';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN TELEPHONE_PRO SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN TELEPHONE_PERSO SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'PHONE_NUMBER';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN TELEPHONE_PERSO SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';

-- NIR (numéro de sécurité sociale) → NATIONAL_IDENTIFIER / IDENTIFIER
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN NIR SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NATIONAL_IDENTIFIER';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN NIR SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';

-- IBAN → BANK_ACCOUNT / IDENTIFIER
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN IBAN SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'BANK_ACCOUNT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN IBAN SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';

-- Date de naissance → DATE_OF_BIRTH / QUASI_IDENTIFIER
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN DATE_NAISSANCE SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'DATE_OF_BIRTH';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN DATE_NAISSANCE SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER';

-- Adresse → US_STREET_ADDRESS (catégorie la plus proche pour une adresse)
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN ADRESSE SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'US_STREET_ADDRESS';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN ADRESSE SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER';

-- Code postal & ville → QUASI_IDENTIFIER
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN CODE_POSTAL SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'US_ZIP_CODE';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN CODE_POSTAL SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN VILLE SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER';

-- Genre & nationalité → SENSITIVE
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN GENRE SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'GENDER';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN GENRE SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'SENSITIVE';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN NATIONALITE SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'SENSITIVE';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL
    ALTER COLUMN LIEU_NAISSANCE SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER';

-- ════════════════════════════════════════════════════════════
-- PARTIE D : POSER LES TAGS MÉTIER (SENSIBILITE + RGPD)
-- ════════════════════════════════════════════════════════════

-- Les system tags (SEMANTIC_CATEGORY, PRIVACY_CATEGORY) sont utiles
-- pour la classification. Mais pour la gouvernance métier, on ajoute
-- nos tags personnalisés créés dans 01_account_setup.

-- TRES_SENSIBLE : données qui identifient directement une personne
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN NOM
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN PRENOM
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN EMAIL_PRO
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN NIR
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN NUMERO_PASSEPORT
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN IBAN
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';

-- SENSIBLE : données de contact / quasi-identifiants
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN TELEPHONE_PRO
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN TELEPHONE_PERSO
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN DATE_NAISSANCE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN PERMIS_CONDUIRE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN ADRESSE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN CODE_POSTAL
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN VILLE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';

-- INTERNE : données RH non directement identifiantes
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN GENRE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'INTERNE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'DONNEE_SENSIBLE';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN NATIONALITE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'INTERNE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'DONNEE_SENSIBLE';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN LIEU_NAISSANCE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'INTERNE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';

-- PUBLIC : données organisationnelles non personnelles
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN DEPARTEMENT
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'PUBLIC',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'NON_PERSONNEL';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN POSTE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'PUBLIC',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'NON_PERSONNEL';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN TYPE_CONTRAT
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'INTERNE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'NON_PERSONNEL';
ALTER TABLE VOLTAIRE_RH.EMPLOYES.PERSONNEL ALTER COLUMN DATE_EMBAUCHE
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'INTERNE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'NON_PERSONNEL';

-- ════════════════════════════════════════════════════════════
-- PARTIE E : CLASSIFIER LES AUTRES TABLES (auto + manual)
-- ════════════════════════════════════════════════════════════

-- Lancer SYSTEM$CLASSIFY sur toutes les tables pour capter
-- les détections automatiques (emails, passeports, etc.).
CALL SYSTEM$CLASSIFY('VOLTAIRE_CRM.CONTACTS.PERSONNES', {'auto_tag': true, 'sample_count': 5000});
CALL SYSTEM$CLASSIFY('VOLTAIRE_CRM.CLIENTS.ENTREPRISES', {'auto_tag': true});
CALL SYSTEM$CLASSIFY('VOLTAIRE_RH.PAIE.BULLETINS', {'auto_tag': true});
CALL SYSTEM$CLASSIFY('VOLTAIRE_RH.RECRUTEMENT.CANDIDATS', {'auto_tag': true});
CALL SYSTEM$CLASSIFY('VOLTAIRE_FINANCE.COMPTABILITE.FACTURES', {'auto_tag': true});
CALL SYSTEM$CLASSIFY('VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS', {'auto_tag': true});
CALL SYSTEM$CLASSIFY('VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS', {'auto_tag': true});

-- Compléments manuels sur les tables les plus critiques :

-- CRM CONTACTS — noms, téléphones, adresse
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES ALTER COLUMN NOM
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES ALTER COLUMN PRENOM
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES ALTER COLUMN TELEPHONE_PORTABLE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'PHONE_NUMBER',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES ALTER COLUMN TELEPHONE_FIXE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'PHONE_NUMBER',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES ALTER COLUMN DATE_NAISSANCE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'DATE_OF_BIRTH',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES ALTER COLUMN ADRESSE_PERSO
    SET TAG VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_CRM.CONTACTS.PERSONNES ALTER COLUMN GENRE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'GENDER',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'SENSITIVE',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'INTERNE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'DONNEE_SENSIBLE';

-- BULLETINS DE PAIE — salaires et IBAN
ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS ALTER COLUMN SALAIRE_BRUT
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'SALARY',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'SENSITIVE',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'DONNEE_SENSIBLE';
ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS ALTER COLUMN SALAIRE_NET
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'SALARY',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'SENSITIVE',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'DONNEE_SENSIBLE';
ALTER TABLE VOLTAIRE_RH.PAIE.BULLETINS ALTER COLUMN IBAN_VERSEMENT
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'BANK_ACCOUNT',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';

-- CANDIDATS — données de recrutement
ALTER TABLE VOLTAIRE_RH.RECRUTEMENT.CANDIDATS ALTER COLUMN NOM
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_RH.RECRUTEMENT.CANDIDATS ALTER COLUMN PRENOM
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';
ALTER TABLE VOLTAIRE_RH.RECRUTEMENT.CANDIDATS ALTER COLUMN TELEPHONE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'PHONE_NUMBER',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.RECRUTEMENT.CANDIDATS ALTER COLUMN DATE_NAISSANCE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'DATE_OF_BIRTH',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';
ALTER TABLE VOLTAIRE_RH.RECRUTEMENT.CANDIDATS ALTER COLUMN SALAIRE_SOUHAITE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'SALARY',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'SENSITIVE',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'INTERNE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'DONNEE_SENSIBLE';

-- FACTURES — IBAN
ALTER TABLE VOLTAIRE_FINANCE.COMPTABILITE.FACTURES ALTER COLUMN IBAN_CLIENT
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'BANK_ACCOUNT',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';

-- TRANSACTIONS — IBAN
ALTER TABLE VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS ALTER COLUMN IBAN_CONTREPARTIE
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'BANK_ACCOUNT',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'TRES_SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'IDENTIFIANT_DIRECT';

-- ACCESS_LOGS — email et IP
ALTER TABLE VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS ALTER COLUMN IP_ADDRESS
    SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'IP_ADDRESS',
        SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER',
        VOLTAIRE_GOVERNANCE.TAGS.SENSIBILITE = 'SENSIBLE',
        VOLTAIRE_GOVERNANCE.TAGS.RGPD = 'QUASI_IDENTIFIANT';

-- ════════════════════════════════════════════════════════════
-- PARTIE F : RÉSUMÉ CROSS-DATABASE — AVANT / APRÈS
-- ════════════════════════════════════════════════════════════

-- Vue d'ensemble : toutes les colonnes taggées dans l'environnement.
SELECT 'VOLTAIRE_RH.EMPLOYES.PERSONNEL' AS TABLE_NAME, TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_RH.EMPLOYES.PERSONNEL','TABLE'))
UNION ALL
SELECT 'VOLTAIRE_CRM.CONTACTS.PERSONNES', TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_CRM.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_CRM.CONTACTS.PERSONNES','TABLE'))
UNION ALL
SELECT 'VOLTAIRE_CRM.CLIENTS.ENTREPRISES', TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_CRM.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_CRM.CLIENTS.ENTREPRISES','TABLE'))
UNION ALL
SELECT 'VOLTAIRE_RH.PAIE.BULLETINS', TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_RH.PAIE.BULLETINS','TABLE'))
UNION ALL
SELECT 'VOLTAIRE_RH.RECRUTEMENT.CANDIDATS', TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_RH.RECRUTEMENT.CANDIDATS','TABLE'))
UNION ALL
SELECT 'VOLTAIRE_FINANCE.COMPTABILITE.FACTURES', TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_FINANCE.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_FINANCE.COMPTABILITE.FACTURES','TABLE'))
UNION ALL
SELECT 'VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS', TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_FINANCE.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_FINANCE.TRESORERIE.TRANSACTIONS','TABLE'))
UNION ALL
SELECT 'VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS', TAG_NAME, TAG_VALUE, COLUMN_NAME
FROM TABLE(VOLTAIRE_DATALAKE.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_DATALAKE.RAW.ACCESS_LOGS','TABLE'))
ORDER BY TABLE_NAME, COLUMN_NAME, TAG_NAME;

-- Comptage par tag personnalisé :
SELECT TAG_NAME, TAG_VALUE, COUNT(*) AS NB_COLONNES
FROM (
    SELECT TAG_NAME, TAG_VALUE FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_RH.EMPLOYES.PERSONNEL','TABLE'))
    UNION ALL
    SELECT TAG_NAME, TAG_VALUE FROM TABLE(VOLTAIRE_CRM.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_CRM.CONTACTS.PERSONNES','TABLE'))
    UNION ALL
    SELECT TAG_NAME, TAG_VALUE FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_RH.PAIE.BULLETINS','TABLE'))
    UNION ALL
    SELECT TAG_NAME, TAG_VALUE FROM TABLE(VOLTAIRE_RH.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('VOLTAIRE_RH.RECRUTEMENT.CANDIDATS','TABLE'))
)
WHERE TAG_NAME IN ('SENSIBILITE', 'RGPD')
GROUP BY TAG_NAME, TAG_VALUE
ORDER BY TAG_NAME, TAG_VALUE;
